### ISSUE TITLE
compareMS2 Histogram not symmetric

### ISSUE THREAD

**Issue by 524D** [magnuspalmblad/compareMS2#10]
The command line compareMS2 produces a different histogram in the `output.txt` file when data files are swapped. Since the computation should be symmetric, this is not expected.

```bash
./compareMS2.exe -A 100913.LC4.IT4.EC.S01540_1-A,8_01_1006.mgf -B ECXX/100913.LC4.IT4.EC.S01540_1-A,8_01_1007.mgf -o outputAB.txt
./compareMS2.exe -B 100913.LC4.IT4.EC.S01540_1-A,8_01_1006.mgf -A ECXX/100913.LC4.IT4.EC.S01540_1-A,8_01_1007.mgf -o outputBA.txt
diff outputAB.txt outputBA.txt

```
Produces:

--- cut ---
```
< histogram     0.340   0.350   0.345   8578    0
< histogram     0.350   0.360   0.355   9564    0
< histogram     0.360   0.370   0.365   10886   0
---
> histogram     0.330   0.340   0.335   8042    0
> histogram     0.340   0.350   0.345   8576    0
> histogram     0.350   0.360   0.355   9566    0
> histogram     0.360   0.370   0.365   10884   0
```
(rest of output removed.

This is probably due to a missing (or superfluous) code line. 
```
A[j].intensity[k] = A[j].intensity[k] / rootSquareSum;
```
from line 640 (commit [da33ae8](https://github.com/magnuspalmblad/compareMS2/commit/da33ae88b01dbebec05c3025e5fd52b095ce2843)) for file A is missing near line 669 for file B.

Strangely, the computed distance still seems symmetric/not effected by swapping the input files.

**Comment by magnuspalmblad** [comment]
Indeed, there is a line missing near line 669 for dataset B - will fix!

**Comment by magnuspalmblad** [comment]
Issue was with maxPeaks not being properly calculated for dataset B. Fixed.
