### ISSUE TITLE
Experimental features weirdness

### ISSUE THREAD

**Issue by 524D** [magnuspalmblad/compareMS2#11]
The computation for the "experimentalFeatures" for data file A is not replicated for data file B. Since the code should be symmetric, this seems incorrect.

Near line 746 (commit [da33ae8](https://github.com/magnuspalmblad/compareMS2/commit/da33ae88b01dbebec05c3025e5fd52b095ce2843))

```
	if (experimentalFeatures == 1)
		massDiffDotProductHistogram[(int) (MASS_DIFF_HISTOGRAM_BINS
				/ 2)
				+ (int) floor(
						(B[j].precursorMz - A[i].precursorMz)
								* 999.99999999999999999)][(int) (HISTOGRAM_BINS
				/ 2) /* constant scaling 1 bin = 0.01 m/z units */
		+ (int) floor(dotProd * (HISTOGRAM_BINS / 2 - 1E-9))]++;


```

Also, the `* 999.99999999999999999` probably does not do what is intended: it is rounded to the nearest value that can be represented as a double. Since the precision is about 17 digits, the result is simply 1000.

**Comment by magnuspalmblad** [comment]
This experimental feature is intended to also look at assymetries in mass measurements and tandem mass spectra between runs, and is asymmetric by definition. The float value as been changed to be within double precision.
