### ISSUE TITLE
Options minBasepeakIntensity and minTotalIntensity are unused in compareMS2.c

### ISSUE THREAD

**Issue by 524D** [magnuspalmblad/compareMS2#5]
In `compareMS2.c,` the options `minBasepeakIntensity `and `minTotalIntensity `(that can be set with the `-m` parameter) are both unused.
This becomes clear by compiling with warnings enabled: `gcc -Wall -o compareMS2 compareMS2.c`

**Comment by magnuspalmblad** [comment]
With `./compareMS2 -A 100913.LC4.IT4.EC.S01540_1-A,8_01_1006.mgf -B 100913.LC4.IT4.EC.S01540_1-A,8_01_1007.mgf -o test -m30000,300000` you can see that some low-intensity spectra are removed from the comparison.

**Comment by 524D** [comment]
Seems to work fine indeed 👍
