### ISSUE TITLE
Output of compareMS2 inconsistent

### ISSUE THREAD

**Issue by 524D** [magnuspalmblad/compareMS2#7]
In the output of compareMS2, the values of `min_basepeak_intensity` and `min_total_ion_current` are separated by a `=` character instead of a tab (which is used for other values):

```
min_basepeak_intensity=10000.00
min_total_ion_current=0.00

```
Also, line with `n_m/z_bins` is duplicated

**Comment by magnuspalmblad** [comment]
Fixed!
