### ISSUE TITLE
Curly bracket missing

### ISSUE THREAD

**Issue by 524D** [magnuspalmblad/compareMS2#8]
The current GitHub version of compareMS2.c doesn't compile. It seems a curly bracket has disappeared in the line below. 

https://github.com/magnuspalmblad/compareMS2/blob/3c5a1b2b129425c1d48aedcf2bb4eb969a2a9cd4/external_binaries/compareMS2.c#L891

**Comment by magnuspalmblad** [comment]
Odd that it disappeared. But it should be back now!
